### ISSUE TITLE
Use .gitlab-ci dotenv to pass credentials between stages

### ISSUE THREAD

**Issue by arongate** [Orange-OpenSource/AWSTerraformStarterKit#36]
Gilab provides dotenv handling between jobs using `artifacts` and `dependencies` keywords in a CICD pipeline code. It looks like following

```yml
my_job:
  stage: build
  script:
    - echo "ENV_VAR=content" >> .env
  artifacts:
    reports:
      dotenv: .env

anotherjob:
  stage: deploy
  script:
    - echo $ENV_VAR
  dependencies:
    - job: my_job
      artifacts: true
```
