### ISSUE TITLE
[enhancement] add mechanism to specify dependency between plans

### ISSUE THREAD

**Issue by arongate** [Orange-OpenSource/AWSTerraformStarterKit#69]
Add mechanism to specify dependencies between plans for example by adding optional `depends_on` which will be populated with a list of plan it depends on. For example:
```yaml
plans:
- terraform/demo0
- terraform/demo1
  depends_on:
    - terraform/demo0
```
This could be a usefull feature to faster gitlab pipeline by specifying dependency only to job they depends on
