### ISSUE TITLE
[enhancement] add a mechanism to allow project specific custom template

### ISSUE THREAD

**Issue by arongate** [Orange-OpenSource/AWSTerraformStarterKit#73]
This is a feature request to add a mechanism to allow project specific custom template with their target rendered file location generates using the project configurations variables.

**Proposal**
Something like this

```yaml
...
templates:
- source: templates/github-actions.yaml.j2
  target: .github-actions/workflow.yaml
- source: templates/.env-project.j2
  target: .env-project
...
```
