### ISSUE TITLE
[enhancements] Gitlab-Ci: Add optional AWS Programatic accesses (Access Key/Secret key) variables configuration

### ISSUE THREAD

**Issue by arongate** [Orange-OpenSource/AWSTerraformStarterKit#87]
In `configure.yaml` and `gitlab-ci.yml.j2` and optional  AWS Programatic access. 

In the `configure.yaml` this could looks like this:

```yaml
...
gitlab_aws_programatic_access:
  enabled: true
  aws_access_key_id_value: $AWS_RECETTE_ACCESS_KEY_ID
  aws_secret_access_key_value: $AWS_RECETTE_SECRET_ACCESS_KEY
...
```

In the generated `gitlab-ci.yml` this would then looks like:

```yaml
variables:
  AWS_ACCESS_KEY_ID: $AWS_RECETTE_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_RECETTE_SECRET_ACCESS_KEY
```
